//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookSales.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.OrderConsist = new HashSet<OrderConsist>();
            this.PlaceHolder = new HashSet<PlaceHolder>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> authorId { get; set; }
        public Nullable<int> genreId { get; set; }
        public Nullable<int> publisherId { get; set; }
        public int pages { get; set; }
        public System.DateTime releaseDate { get; set; }
        public decimal retailPrice { get; set; }
        public byte[] image { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Genres Genres { get; set; }
        public virtual Publishers Publishers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderConsist> OrderConsist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaceHolder> PlaceHolder { get; set; }
    }
}
