//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookSales
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookSalesEntities : DbContext
    {
        public BookSalesEntities()
            : base("name=BookSalesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<OrderConsist> OrderConsist { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<PlaceHolder> PlaceHolder { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Publishers> Publishers { get; set; }
        public virtual DbSet<Storage> Storage { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
